### ISSUE TITLE
단어 불러오기

### ISSUE THREAD

**Issue by alack** [alack/BrainReader#10]
단어 불러오기이이이이이ㅣ이이ㅣ이이이ㅣ

**Comment by alack** [comment]
complete!!!

**Comment by alack** [comment]
단어 추가는 postman을 통해 localhost:3000/room/addWord로 {word:something, description:blah~}를 보내면 됨

**Comment by yoojaehong92** [comment]
카테고리도 있어야함

**Comment by yoojaehong92** [comment]
localhost:3000/room/addWord 이 아니라
localhost:3000/word/addWord 인 것 같음!
```
>use web-system-design
>db.words.insert({word:"사과", description:""})
```
위와 같이 하면 될듯??

**Comment by alack** [comment]
ㅇㅇㅇㅇ word.js 파일 분리전이라 그랬음
