### ISSUE TITLE
디렉토리 & 파일 이름 일관성 있게 고쳐야할듯?

### ISSUE THREAD

**Issue by yoojaehong92** [alack/BrainReader#17]
# ppap!!!!!

**Comment by alack** [comment]
동의 그리고 component마다 폴더로 묶었으면 좋겠음

**Comment by yoojaehong92** [comment]
ㅇㅇ component 별로 파일이 보통 3개씩있으니까 보기 힘드네

**Comment by alack** [comment]
대충 내가 분류할 수 있는 정도만 정리함.... 자기 파트 정리 부탁

**Comment by alack** [comment]
아무도 안하니 다한걸로 간주하겠음.
