### ISSUE TITLE
겜 프로세스 작성

### ISSUE THREAD

**Issue by alack** [alack/BrainReader#34]
content 내일 기록해두겠슴니다.

**Comment by alack** [comment]
1. 게임방 입장
2. ㄹㄷ 누름
3. 모든 유저가 ㄹㄷ상태가 되면 색을 모두 해제 후

**Comment by crosstreet74** [comment]
단어 입력없이 ready 완료 시 null 값 전달 오류

**Comment by alack** [comment]
3. 색을 모두 해제 후 게임 시작 event를 보냄 상호간의 그림 공유, 정답 맞추기를 가능케 하는 함수 작동
시간을 초기화 함
4. 랜덤으로 한명의 유저를 선택해서 그림그릴권한을 주고 단어를 불러오게함
5. 권한을 가진 사람은 그림을 그린다. 그러면 접속한 자들에게 모두 공유됨
5-1. 답을 맞출 시 시간을 초기화, curcnt를 하나 올려 현재 게임 스테이지를 하나 증가시킴, 맞춘 사람에게 그림 그릴 권한이 넘어감, 지정된 유저에게 넘어가는 것을 제외하고 4번부터 process 시작
5-2. 답을 맞춘 사람이 없을 경우, 4번부터 수행
6. gamecnt를 curcnt가 넘을 경우 해당 game이 끝남. 모두의 ready상태가 해제되고, 다시 ㄹㄷ후 게임 가능.
